language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.2
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ree
env:
  matrix:
    - "TASK=test"
    - "TASK=bench"
  allowed_failures:
    env:
      - "TASK=bench"
script: "bundle exec rake $TASK"
